spring:
  data:
    mongodb:
      authentication-database: admin
      username: restaurant
      host: localhost
      port: 27017
      password: restaurant
application:
  security:
    expiration: '84600000'
    secretKey: dUJvTlpIWlAwb3JqeWk4YnRuTHd5cVFXVW1uaW5XS0hGeWUrOXRPYTdjWT0=
    refreshToken:
      expiration: '604800000'